name: Mirror to GitLab

on:
  push:
    branches: [ "*" ]
  create:
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Bare clone and push to GitLab
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: "gitlab.com/xx-hex-xx/Trainers.git"
        run: |
          git clone --bare https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git mirror.git
          cd mirror.git
          git push --mirror https://$GITLAB_USERNAME:$GITLAB_TOKEN@$GITLAB_REPO
