name: Mirror to GitLab

on:
  push:
    branches: [ "*" ]
  create:
    tags:
      - "*"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Важно для подтягивания всей истории

      - name: Push to GitLab
        env:
          GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: "gitlab.com/ваш_юзернейм/ваш_репозиторий.git" # Укажите ваш путь
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote add gitlab https://$GITLAB_USERNAME:$GITLAB_TOKEN@$GITLAB_REPO
          git push gitlab --mirror
